name: minigame-spawn
version: 0.1
main: com.rrayy.spawn.spawn
api-version: 1.19
description: 미니게임을 위한 팀 스폰 기능의 플러그인
commands:
  delay:
    description: 리스폰 딜레이를 수정합니다
    usage: /delay + (딜레이 시간/초)
  kit:
    description: 기본 지급 아이템을 얻습니다
    usage: /kit